[package]
name = "dbms_proj_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
serde = "1.0.204"
sqlx = { version = "0.7.4", features = ["runtime-tokio", "postgres", "uuid"] }
